[general]
library_name = "libpsr_database_c"
output_file_path = "../src/c_api.jl"
module_name = "C"
# jll_pkg_name = "PSRDatabase_jll"
print_using_CEnum = false
prologue_file_path = "./prologue.jl"
epilogue_file_path = "./epilogue.jl"
output_ignorelist = [
]

[codegen]
use_julia_bool = true
use_ccall_macro = true
opaque_func_arg_as_PtrCvoid = true
