name = "Quiver"
uuid = "3bd9c58c-5d43-42f3-8ca0-6ca814cf6d36"
version = "0.2.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
Aqua = "0.8"
CEnum = "0.5"
DataFrames = "1"
Dates = "1"
JSON3 = "1"
Libdl = "1"
Test = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
